# Check code quality with eslint.
name: Testing

on:
  # Triggers the workflow on push or pull request events.
  push:
    branches-ignore: ["gh-pages"]
  pull_request:
    branches: ["production", "development"]

jobs:
  eslint:
    name: ESLint linter
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v3

      - name: Install 🗃️
        run: npm install

      - name: Run ESLint 🕵️
        run: npm run lint
